project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Météo"
  page-navigation: true
  repo-url: https://github.com/MaxenceLamure/PersonalProject
  repo-actions: [source, issue]
  
  navbar:
    tools: 
      - icon: github
        href: https://github.com/MaxenceLamure/PersonalProject
        text: GitHub
    left:
      - href: index.qmd
        text: Accueil
         
execute:
  echo: false  

format:
  html:
    theme: cerulean
jupyter: python3